<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Klanak_model extends CI_Model
{

    public $table = 'klanak';
    public $id = 'IDA';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('IDA', $q);
	$this->db->or_like('nanak', $q);
	$this->db->or_like('wktla', $q);
	$this->db->or_like('tmel', $q);
	$this->db->or_like('jklh', $q);
	$this->db->or_like('bbdn', $q);
	$this->db->or_like('pjbdn', $q);
	$this->db->or_like('ankke', $q);
	$this->db->or_like('tmptkll', $q);
	$this->db->or_like('namasu', $q);
	$this->db->or_like('agma', $q);
	$this->db->or_like('umro', $q);
	$this->db->or_like('pkjan', $q);
	$this->db->or_like('naist', $q);
	$this->db->or_like('agmas', $q);
	$this->db->or_like('umris', $q);
	$this->db->or_like('pkjanis', $q);
	$this->db->or_like('blok', $q);
	$this->db->or_like('rtort', $q);
	$this->db->or_like('rworts', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('IDA', $q);
	$this->db->or_like('nanak', $q);
	$this->db->or_like('wktla', $q);
	$this->db->or_like('tmel', $q);
	$this->db->or_like('jklh', $q);
	$this->db->or_like('bbdn', $q);
	$this->db->or_like('pjbdn', $q);
	$this->db->or_like('ankke', $q);
	$this->db->or_like('tmptkll', $q);
	$this->db->or_like('namasu', $q);
	$this->db->or_like('agma', $q);
	$this->db->or_like('umro', $q);
	$this->db->or_like('pkjan', $q);
	$this->db->or_like('naist', $q);
	$this->db->or_like('agmas', $q);
	$this->db->or_like('umris', $q);
	$this->db->or_like('pkjanis', $q);
	$this->db->or_like('blok', $q);
	$this->db->or_like('rtort', $q);
	$this->db->or_like('rworts', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Klanak_model.php */
/* Location: ./application/models/Klanak_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-10 10:45:32 */
/* http://harviacode.com */